version: '3'

volumes:
  <app-name>-mysql-data:
    driver: local

services:
  mysql:
    image: mysql:latest
    container_name: <app-name>-mysql
    volumes:
      - <app-name>-mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: <app-name>
      MYSQL_DATABASE: <app-name>
      MYSQL_USER: <app-name>
      MYSQL_PASSWORD: <app-name>

  app:
    image: uspdev/php-sybase:0.9
    container_name: <app-name>-app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    restart: always
    tty: true
    links:
      - mysql
